
name: upload sarif report
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
permissions:
  security-events: write
  contents: read
jobs:
  sec:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      # Your steps to generate the SARIF file go here

      - name: List files in current directory
        run: ls -la
      - name: Generate SARIF report
        run: |
          python3 build_sarif_from_json.py -j semgrep.json -s semgrep.sarif
      - name: Check SARIF file size
        run: du -h semgrep.sarif
      
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: semgrep.sarif
