
name: upload sarif report
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  sec:
    runs-on: ubuntu-latest
    steps:
      - name: Upload Sarif file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: semgrep.sarif
